added missing space

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -62,20 +62,17 @@ before_install:
 
 
 install:
-  - conda env create -n test python=$PYTHON_VER -f devtools/conda-envs/cmiles.yaml
-#  - |
-#    if [ $ENVIRON == "RDKIT"]; then
-#      echo "RDKIT env"
-#      conda env create -n test python=$PYTHON_VER -f devtools/conda-envs/rdkit-2018.yaml
-#      echo "Build RDKIT env"
-#    elif [ $ENVIRON == "OPENEYE"]; then
-#      conda env create -n test python=$PYTHON_VER -f devtools/conda-envs/openeye-2018.yaml
-#    elif [ $ENVIRON == "CMILES"]; then
-#      conda env create -n test python=$PYTHON_VER -f devtools/conda-envs/cmiles.yaml
-#    else
-#      echo "ERROR: No match for ENVIRON ($ENVIRON)."
-#      exit 1
-#    fi
+  - |
+    if [ $ENVIRON == "RDKIT" ]; then
+      conda env create -n test python=$PYTHON_VER -f devtools/conda-envs/rdkit-2018.yaml
+    elif [ $ENVIRON == "OPENEYE" ]; then
+      conda env create -n test python=$PYTHON_VER -f devtools/conda-envs/openeye-2018.yaml
+    elif [ $ENVIRON == "CMILES" ]; then
+      conda env create -n test python=$PYTHON_VER -f devtools/conda-envs/cmiles.yaml
+    else
+      echo "ERROR: No match for ENVIRON ($ENVIRON)."
+      exit 1
+    fi
   - source activate test
   - python setup.py develop --no-deps
 
